### ISSUE TITLE
weka-mon prometheus scraping timing out- on ice to make sure metrics are consistent

### ISSUE THREAD

**Issue by trent-safe-ai** [centerforaisafety/cerberus-cluster#200]

**Comment by trent-safe-ai** [comment]
instance running wekamon seems to die after a time trying to connect to loki- which I'm not sure which loki its thinking it needs to be connected to- will follow up with Weka tomorrow. 

Instance is back up for now- changed the export config to this- referring to the actual loki we use. Its confusing because we are JUST running the export binary not the entire prometheus, grafana, loki, weka-mon suite they recommend if you don't already have a monitoring platform.  Can't determine if the export binary is trying to connect to some other loki- dont know.

Changes wekamon is in the observabiolity compartment- 10.0.1.136 config to this- 
```
exporter:
  listen_port: 8001
  loki_host: loki-gateway.operator.cais.oraclevcn.com
  loki_port: 3100
  loki_tenant: watchtower
  timeout: 10.0
  max_procs: 1
  max_threads_per_proc: 100
  backends_only: True
  datapoints_per_collect: 5
```
