### ISSUE TITLE
Update playbooks to not update node state when state is `mix`

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#270]
The play below updates a nodes state if it isn't in an `idle` or `alloc` state. We would also like for the play to not update the state when it's in a `mix` state. 

```yml
- name: Update node state on bastion
  block:
    - name: Grab Node State
      shell: 'sinfo -h -o "%t" -n {{ ansible_hostname }}'
      register: node_state
      delegate_to: 127.0.0.1
    - set_fact:
        node_state2: "{{ node_state.stdout }}"
    - name: Update node state on bastion
      become: true
      command: scontrol update nodename={{ ansible_hostname }} state=RESUME
      when: node_state2 != "idle" and node_state2 != "alloc"
  rescue:
    - name: Sleep 5 seconds
      pause: 
        seconds: 10

    - name: Grab Node State
      shell: 'sinfo -h -o "%t" -n {{ ansible_hostname }}'
      register: node_state
      delegate_to: 127.0.0.1
      until: node_state.stdout.find("failure") == -1
      retries: 10
      delay: 5
```
