### ISSUE TITLE
Update `Update node state on bastion` with `become: true` to view nodes in hidden partitions

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#271]
The below play returns a list of compute node names on our cluster but because it isn't run as root then it won't return node in hidden partitions. We have a few plays like this.  

```yml    
- name: Grab Node State
   shell: 'sinfo -h -o "%t" -n {{ ansible_hostname }}'
   register: node_state
   delegate_to: 127.0.0.1
```
