### ISSUE TITLE
Update destination ip subnet mask in iptables playbook

### ISSUE THREAD

**Issue by andriy-safe-ai** [centerforaisafety/cerberus-cluster#313]
Update the destination ip subnet mask in `iptables` role to `10.0.0.0/21`.

The specific play in question:
```yml
    - name: Append rule to USER_TRAFFIC chain
      iptables:
        table: filter
        chain: USER_TRAFFIC
        destination: 172.16.0.0/21
        jump: RETURN
        action: append
```
