### ISSUE TITLE
Remove devtoolset-5 from cais-compute playbook

### ISSUE THREAD

**Issue by xksteven** [centerforaisafety/cerberus-cluster#41]
Yum can't seem to find the package anymore.  Alternatively other than removing find out why it can't be found.

**Comment by andriy-safe-ai** [comment]
@steven-basart 

The reason we don't see `devtoolset-5` is because this release doesn't appear to exist. 

This links to all the releases for `devtoolset`: https://www.softwarecollections.org/en/scls/tag/devtoolset/ 
There doesn't appear to be a version 5.

**Comment by steven-basart** [comment]
It used to exist. I installed it and it's installed on prod. So it was removed within the last 6 months. I don't know who owns the repository servers. If we're reaching out to public servers or Oracle servers.

**Comment by andriy-safe-ai** [comment]
I don't think it is installed on prod. I ran `sudo yum list installed | grep devtoolset-5` and didn't get any results.

**Comment by steven-basart** [comment]
Maybe I already removed it. 

Make sure to check the compute nodes though. It probably also shouldn't be on bastion but that's not as big of a deal. 

```
18:53:35 opc@watch-tower-bastion:/opt/rh
$ ssh compute-permanent-node-365
Last login: Wed Jul 26 17:43:59 2023 from watch-tower-bastion.public.cluster.oraclevcn.com
18:53:47 opc@compute-permanent-node-365:~
$ cd /opt/rh/
18:53:51 opc@compute-permanent-node-365:/opt/rh
$ ls
devtoolset-10  devtoolset-6  devtoolset-8  rh-nodejs12
devtoolset-12  devtoolset-7  rh-nodejs10   rh-nodejs14
```

**Comment by andriy-safe-ai** [comment]
@steven-basart 

I wrote a short Ansible Playbook to check whether `dev toolset-5` is installed on any of our nodes:
```
---

- name: Check if devtoolset-5 is installed
  hosts: login,bastion,slurm_backup,compute
  become: true
  tasks:
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Check whether a package called devtoolset-5 is installed
      ansible.builtin.debug:
        msg: "{{ ansible_facts.packages['devtoolset-5'] | length }} versions of devtoolset are installed!"
      when: "'devtoolset-5' in ansible_facts.packages"
```

`devtoolset-5` is not installed on any of our nodes.
