### ISSUE TITLE
Update zsh version

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#93]
Current version installed is: zsh 5.0.2 (x86_64-redhat-linux-gnu)

Steps remove the zsh installed and install the new one.  EZ.  (full steps incoming including ansible playbook).  
Requires removing where it's installed in ansible too.

**Comment by steven-basart** [comment]
Test out manually installing it first
Requires curses
```
sudo yum install ncurses-devel
```

```
cd /usr/src/
sudo su
mkdir local
chgrp privilege local/
chmod 775 local/

wget https://www.zsh.org/pub/zsh-5.9.tar.xz

xz -d zsh-5.9.tar.xz
tar xvf zsh-5.9.tar

cd zsh-5.9
./configure && make
sudo make install
```

Confirm it works
```
/usr/local/bin/zsh

$ zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
```

Make the symlink point to the new install
```
sudo rm /bin/zsh
sudo ln -s /usr/local/bin/zsh /bin/zsh
```

Okay everything works with manual testing

**Comment by steven-basart** [comment]
Ansible playbook:

```
# Needed for newer versions of zsh
- name: install ncurses
  vars:
    package_name:
      - ncurses-devel
    package_state: latest
    package_repo: "epel,ol7_developer_epel"
  include_role:
    name: safe_yum
  ignore_errors: true

- name: Create usr/src/local
  become: true
  file:
    path: /usr/src/local
    state: directory
    mode: '0775'
    group: privilege

- name: grab zsh tar file
  become: true
  get_url: https://www.zsh.org/pub/zsh-5.9.tar.xz

- name: untar zsh file
  become: true
  shell: xz -d zsh-5.9.tar.xz && tar xvf zsh-5.9.tar

- name: make zsh
  become: true
  shell: cd /usr/src/local/zsh-5.9 && ./configure && make && make install

- name: Delete old zsh
  become: true
  file:
    path: /bin/zsh
    state: absent

- name: Create a symbolic link
  become: true
  file:
    src: /usr/local/bin/zsh
    dest: /bin/zsh
    owner: root
    group: root
    state: link
```
